name: Build test account management module

on:
  push:
    branches:
      - stag/account-management
  pull_request:

jobs:
  build:
    name: build account management module
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Build the Go application
        run: sh hack/ci/account_management.sh

      - name: Remove binaries
        run: rm -rf bin
